"use client";

import { useMemo, useState, useTransition } from "react";
import type { PageBuilderState } from "@livingsites/application";
import type { Section } from "@livingsites/domain";
import { RegisteredSectionRenderer } from "./section-renderer";
import { addSectionAction, duplicateSectionAction, publishPageAction, removeSectionAction, reorderSectionsAction, updateSectionAction, type BuilderActionResult } from "./actions";

type Props = { readonly organizationId: string; readonly websiteId: string; readonly pageId: string; readonly initialState: PageBuilderState; readonly canPublish?: boolean };
const inputLabel = (key: string) => key.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase());

export function BuilderClient({ organizationId, websiteId, pageId, initialState, canPublish = false }: Props) {
  const [state, setState] = useState(initialState); const [selectedId, setSelectedId] = useState(initialState.sections[0]?.id ? String(initialState.sections[0].id) : null); const [draftProps, setDraftProps] = useState<Record<string, unknown> | null>(initialState.sections[0] ? structuredClone(initialState.sections[0].props) : null); const [notice, setNotice] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const selected = useMemo(() => state.sections.find((section) => String(section.id) === selectedId) ?? null, [state.sections, selectedId]);
  const select = (section: Section) => { setSelectedId(String(section.id)); setDraftProps(structuredClone(section.props)); setNotice(null); };
  const apply = (work: () => Promise<BuilderActionResult>, nextSelection?: string | null) => startTransition(async () => { setNotice(null); const result = await work(); if (!result.ok) { setNotice(result.message); return; } setState(result.state); const id = nextSelection === undefined ? selectedId : nextSelection; setSelectedId(id); const updated = result.state.sections.find((section) => String(section.id) === id); setDraftProps(updated ? structuredClone(updated.props) : null); setNotice("Saved"); });
  const move = (index: number, offset: number) => { const target = index + offset; if (target < 0 || target >= state.sections.length) return; const ids = state.sections.map((section) => String(section.id)); [ids[index], ids[target]] = [ids[target]!, ids[index]!]; apply(() => reorderSectionsAction(organizationId, websiteId, pageId, state.page.version, ids)); };
  const publish = () => startTransition(async () => { setNotice(null); const result = await publishPageAction(organizationId, websiteId, pageId, state.page.version); if (!result.ok) { setNotice(result.message); return; } setNotice(`Published revision ${result.revisionNumber}.`); location.reload(); });

  return <div className="page-builder">
    <header className="builder-topbar"><a href={`/admin/organizations/${organizationId}/websites/${websiteId}/pages`} aria-label="Back to pages">← Pages</a><div><span className="builder-eyebrow">Page builder</span><h1>{state.page.title}</h1></div><div className="builder-status"><span>{state.page.status}{state.page.publishedSnapshotId ? " · live snapshot" : " · not published"}</span><strong aria-live="polite">{pending ? "Working…" : notice ?? "All changes saved"}</strong><a className="builder-history-link" href={`/admin/organizations/${organizationId}/websites/${websiteId}/pages/${pageId}/builder/history`}>Version history</a>{canPublish ? <button className="builder-publish" type="button" disabled={pending || state.page.status !== "draft"} onClick={publish}>Publish</button> : null}</div></header>
    {notice && notice !== "Saved" ? <div className="builder-conflict" role="alert">{notice} {notice.includes("Reload") && <button type="button" onClick={() => location.reload()}>Reload page</button>}</div> : null}
    <div className="builder-workspace">
      <aside className="builder-library" aria-label="Section library"><div className="builder-panel-title"><span>01</span><div><h2>Structure</h2><p>Add and arrange sections</p></div></div><div className="section-add-grid">{state.sectionTypes.map((type) => <button type="button" key={String(type.key)} disabled={!state.canEdit || pending} onClick={() => apply(async () => { const result = await addSectionAction(organizationId, websiteId, pageId, state.page.version, String(type.key)); if (result.ok) { const newest = result.state.sections.at(-1); if (newest) { setSelectedId(String(newest.id)); setDraftProps(structuredClone(newest.props)); } } return result; })}><span>+</span>{type.name}</button>)}</div><ol className="section-list">{state.sections.map((section, index) => { const type = state.sectionTypes.find((candidate) => candidate.id === section.sectionTypeId); return <li key={String(section.id)}><button className={selectedId === section.id ? "selected" : ""} type="button" onClick={() => select(section)}><span>{String(index + 1).padStart(2, "0")}</span>{type?.name ?? "Unknown"}</button><div><button type="button" aria-label={`Move ${type?.name} up`} disabled={!state.canEdit || index === 0 || pending} onClick={() => move(index, -1)}>↑</button><button type="button" aria-label={`Move ${type?.name} down`} disabled={!state.canEdit || index === state.sections.length - 1 || pending} onClick={() => move(index, 1)}>↓</button></div></li>; })}</ol></aside>
      <main className="builder-canvas"><div className="canvas-label"><span>Live draft preview</span><span>Desktop · 1200px</span></div><div className="canvas-page">{state.sections.length ? state.sections.map((section) => <div key={String(section.id)} className={selectedId === section.id ? "canvas-section active" : "canvas-section"} onClick={() => select(section)}><RegisteredSectionRenderer section={section} /></div>) : <div className="canvas-empty"><span>✦</span><h2>Your page starts here</h2><p>Add a section from the library to begin.</p></div>}</div></main>
      <aside className="builder-properties" aria-label="Section properties"><div className="builder-panel-title"><span>02</span><div><h2>Properties</h2><p>{selected ? state.sectionTypes.find((type) => type.id === selected.sectionTypeId)?.name : "Select a section"}</p></div></div>{selected && draftProps ? <form onSubmit={(event) => { event.preventDefault(); apply(() => updateSectionAction(organizationId, websiteId, pageId, state.page.version, String(selected.id), draftProps)); }}><Fields value={draftProps} onChange={setDraftProps} disabled={!state.canEdit || pending} /><button className="builder-save" type="submit" disabled={!state.canEdit || pending}>Save section</button><div className="builder-danger"><button type="button" disabled={!state.canEdit || pending} onClick={() => apply(() => duplicateSectionAction(organizationId, websiteId, pageId, state.page.version, String(selected.id)))}>Duplicate</button><button type="button" disabled={!state.canEdit || pending} onClick={() => apply(() => removeSectionAction(organizationId, websiteId, pageId, state.page.version, String(selected.id)), null)}>Remove</button></div></form> : <p className="properties-empty">Choose a section in the canvas or structure list to edit its content.</p>}</aside>
    </div>
  </div>;
}

function Fields({ value, onChange, disabled }: { readonly value: Record<string, unknown>; readonly onChange: (value: Record<string, unknown>) => void; readonly disabled: boolean }) {
  return <div className="property-fields">{Object.entries(value).map(([key, field]) => Array.isArray(field) ? <fieldset key={key}><legend>{inputLabel(key)}</legend>{field.map((item, index) => <div className="repeatable-item" key={index}>{Object.entries(item as Record<string, unknown>).map(([itemKey, itemValue]) => <label key={itemKey}>{inputLabel(itemKey)}<textarea disabled={disabled} rows={itemKey.toLowerCase().includes("description") ? 3 : 2} value={String(itemValue ?? "")} onChange={(event) => { const next = structuredClone(value); (next[key] as Record<string, unknown>[])[index]![itemKey] = event.target.value; onChange(next); }} /></label>)}<button type="button" disabled={disabled || field.length === 1} onClick={() => onChange({ ...value, [key]: field.filter((_, itemIndex) => itemIndex !== index) })}>Remove item</button></div>)}<button type="button" disabled={disabled} onClick={() => onChange({ ...value, [key]: [...field, Object.fromEntries(Object.keys(field[0] ?? { title: "", description: "" }).map((itemKey) => [itemKey, ""]))] })}>+ Add item</button></fieldset> : <label key={key}>{inputLabel(key)}{String(field).length > 100 || key === "body" || key === "subheading" ? <textarea disabled={disabled} rows={5} value={String(field)} onChange={(event) => onChange({ ...value, [key]: event.target.value })} /> : <input disabled={disabled} type="text" inputMode={key.toLowerCase().includes("url") ? "url" : undefined} value={String(field)} onChange={(event) => onChange({ ...value, [key]: event.target.value })} />}</label>)}</div>;
}
