import { describe, expect, it } from "vitest";
import type { OrganizationId, Page, PageId, Slug, UserId, Website, WebsiteId } from "@livingsites/domain";
import { PageStatus, WebsiteStatus } from "@livingsites/domain";
import { publishPage } from "./publish-page.js";

const orgId = "org_a" as OrganizationId; const websiteId = "web_a" as WebsiteId; const pageId = "page_a" as PageId; const userId = "usr_a" as UserId;
const audit = { createdAt: "2026-08-19T00:00:00.000Z", updatedAt: "2026-08-19T00:00:00.000Z" } as Page["audit"];
const website: Website = { id: websiteId, organizationId: orgId, name: "Site", slug: "site" as Slug, customDomain: null, fallbackDomain: "site.example.com", status: WebsiteStatus.Draft, publishedVersion: null, themeId: null, defaultLocale: "en-US" as never, enabledLocales: ["en-US" as never], settings: { passwordProtection: null, searchEngineIndexing: true, socialDefaults: {}, headerScripts: [], footerScripts: [] }, version: 1, audit, archivedAt: null };
const section = { id: "section_1", pageId, websiteId, sectionTypeId: "section-type:hero", props: { headline: "Hello", subheading: "World", ctaLabel: "Go", ctaUrl: "/contact" }, sortOrder: 0, status: "active", audit } as never;
const page: Page = { id: pageId, websiteId, title: "Home", slug: "home" as Slug, isHomepage: true, status: PageStatus.Draft, publishedSnapshotId: null, sectionOrder: [section.id], sections: [section], availableLocales: [], parentId: null, version: 3, audit, archivedAt: null };
const deps = (overrides: Record<string, unknown> = {}) => ({ authenticatedUser: { userId }, authorizationService: { can: async () => ({ allowed: true }) }, websiteReader: { findById: async () => website }, pageReader: { findById: async () => page }, pagePublisher: { publish: async ({ candidate }: never) => ({ ok: true, value: { ...candidate, revisionNumber: 1, createdAt: candidate.publishedAt, publishedBy: String(candidate.publishedBy) } }) }, clock: { nowIso: () => "2026-08-19T12:00:00.000Z" }, idGenerator: { generatePrefixed: () => "snapshot_1" }, ...overrides }) as never;

describe("PublishPage", () => {
  it("authorizes, validates, and sends an immutable publication candidate", async () => { const result = await publishPage({ organizationId: orgId, websiteId, pageId, expectedVersion: 3 }, deps()); expect(result.ok && result.value.revisionNumber).toBe(1); });
  it("denies viewers and cross-organization ownership", async () => { expect((await publishPage({ organizationId: orgId, websiteId, pageId, expectedVersion: 3 }, deps({ authorizationService: { can: async () => ({ allowed: false, reason: "Denied" }) } }))).ok).toBe(false); expect((await publishPage({ organizationId: "org_b" as OrganizationId, websiteId, pageId, expectedVersion: 3 }, deps())).ok).toBe(false); });
  it("denies wrong Website/Page combinations and archived Websites", async () => { expect((await publishPage({ organizationId: orgId, websiteId, pageId, expectedVersion: 3 }, deps({ pageReader: { findById: async () => ({ ...page, websiteId: "web_b" }) } }))).ok).toBe(false); expect((await publishPage({ organizationId: orgId, websiteId, pageId, expectedVersion: 3 }, deps({ websiteReader: { findById: async () => ({ ...website, status: WebsiteStatus.Archived }) } }))).ok).toBe(false); });
  it("rejects malicious URLs before persistence", async () => { let called = false; const result = await publishPage({ organizationId: orgId, websiteId, pageId, expectedVersion: 3 }, deps({ pageReader: { findById: async () => ({ ...page, sections: [{ ...section, props: { ...section.props, ctaUrl: "javascript:alert(1)" } }] }) }, pagePublisher: { publish: async () => { called = true; throw new Error("unexpected"); } } })); expect(result.ok).toBe(false); expect(called).toBe(false); });
  it("surfaces stale versions without writing", async () => { let called = false; const result = await publishPage({ organizationId: orgId, websiteId, pageId, expectedVersion: 2 }, deps({ pagePublisher: { publish: async () => { called = true; throw new Error("unexpected"); } } })); expect(result.ok).toBe(false); expect(called).toBe(false); });
});
