import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { NetlifyDB } from "@netlify/database-dev";
import { drizzle } from "drizzle-orm/postgres-js";
import { eq } from "drizzle-orm";
import postgres from "postgres";
import type { ISODateString, OrganizationId, PageArchivedEvent, PageCreatedEvent, PageId, PageRestoredEvent, Section, SectionId, SectionTypeId, Slug, UserId, WebsiteHomepageChangedEvent, WebsiteId } from "@livingsites/domain";
import { createPageDraft } from "@livingsites/domain";
import { NoopLogger } from "@livingsites/platform";
import * as schema from "../../db/schema.js";
import { applicationOutbox, organizations, pages, websites } from "../../db/schema.js";
import { DrizzlePageRepository } from "./drizzle-page-repository.js";

const orgId = "org_pages" as OrganizationId; const websiteId = "web_pages" as WebsiteId; const now = "2026-08-19T00:00:00.000Z" as ISODateString; const userId = "usr_owner" as UserId;
const draft = (id: string, slug = "about") => createPageDraft({ id: id as PageId, websiteId, title: "About", slug: slug as Slug, now, createdBy: userId });
const createdEvent = (id: PageId): PageCreatedEvent => ({ type: "page.created", occurredAt: now, eventScope: { scope: "website", organizationId: orgId, websiteId }, pageId: id, slug: "about" });
const archivedEvent = (id: PageId): PageArchivedEvent => ({ type: "page.archived", occurredAt: now, eventScope: { scope: "website", organizationId: orgId, websiteId }, pageId: id });
const restoredEvent = (id: PageId): PageRestoredEvent => ({ type: "page.restored", occurredAt: now, eventScope: { scope: "website", organizationId: orgId, websiteId }, pageId: id });
const homepageEvent = (id: PageId): Omit<WebsiteHomepageChangedEvent, "previousHomepagePageId" | "pageVersion"> => ({ type: "website.homepage_changed", occurredAt: now, eventScope: { scope: "website", organizationId: orgId, websiteId }, pageId: id });

describe("DrizzlePageRepository — Netlify Database", () => {
  let netlifyDB: NetlifyDB; let sqlClient: ReturnType<typeof postgres>; let db: ReturnType<typeof drizzle<typeof schema>>; let repository: DrizzlePageRepository;
  beforeAll(async () => { netlifyDB = new NetlifyDB({ logger: () => {} }); const connectionString = await netlifyDB.start(); await netlifyDB.applyMigrations("./netlify/database/migrations"); sqlClient = postgres(connectionString, { max: 1 }); await sqlClient`select set_config('app.context_mode', 'internal', false)`; await sqlClient`select set_config('app.tenant_authorized', 'true', false)`; db = drizzle({ client: sqlClient, schema }); repository = new DrizzlePageRepository({ db, logger: new NoopLogger() }); });
  afterAll(async () => { await sqlClient.end(); await netlifyDB.stop(); });
  beforeEach(async () => { await db.delete(applicationOutbox); await db.delete(pages); await db.delete(websites); await db.delete(organizations); await db.insert(organizations).values({ id: orgId, name: "Pages Org", slug: "pages-org", billing_email: "pages@example.com", status: "active", feature_overrides: "[]", version: 1, created_at: new Date(now), updated_at: new Date(now) }); await db.insert(websites).values({ id: websiteId, organization_id: orgId, name: "Pages", slug: "pages", fallback_domain: "pages.example.com", status: "draft", default_locale: "en-US", enabled_locales: ["en-US"], settings: { passwordProtection: null, searchEngineIndexing: true, socialDefaults: {}, headerScripts: [], footerScripts: [] }, version: 1, created_at: new Date(now), updated_at: new Date(now) }); });

  it("creates version one, lists, gets, and enforces active slug uniqueness", async () => { const candidate = draft("page_a"); const created = await repository.createWithEvent(candidate, createdEvent(candidate.id)); expect(created.ok && created.value.version).toBe(1); expect((await repository.findById(candidate.id))?.title).toBe("About"); expect(await repository.listForWebsite(websiteId)).toHaveLength(1); expect((await repository.createWithEvent(draft("page_b"), createdEvent("page_b" as PageId))).ok).toBe(false); });
  it("uses optimistic concurrency for details", async () => { const candidate = draft("page_update"); await repository.createWithEvent(candidate, createdEvent(candidate.id)); const updated = await repository.updateDetails({ pageId: candidate.id, title: "About us", slug: "about-us", expectedVersion: 1, updatedAt: now, updatedBy: userId }); expect(updated.ok && updated.value.version).toBe(2); expect((await repository.updateDetails({ pageId: candidate.id, title: "Stale", slug: "stale", expectedVersion: 1, updatedAt: now, updatedBy: userId })).ok).toBe(false); });
  it("atomically persists Page-owned Sections and increments Page.version", async () => { const candidate = draft("page_builder_save"); await repository.createWithEvent(candidate, createdEvent(candidate.id)); const section: Section = { id: "section_1" as SectionId, pageId: candidate.id, websiteId, sectionTypeId: "section-type:hero" as SectionTypeId, sortOrder: 0, status: "active", props: { headline: "Hello", subheading: "World", ctaLabel: "Go", ctaUrl: "#" }, audit: { createdAt: now, updatedAt: now, createdBy: userId, updatedBy: userId } }; const saved = await repository.saveBuilder({ pageId: candidate.id, sections: [section], expectedVersion: 1, updatedAt: now, updatedBy: userId }); expect(saved.ok && saved.value.version).toBe(2); const reloaded = await repository.findById(candidate.id); expect(reloaded?.sections).toHaveLength(1); expect(reloaded?.sectionOrder).toEqual([section.id]); const stale = await repository.saveBuilder({ pageId: candidate.id, sections: [], expectedVersion: 1, updatedAt: now, updatedBy: userId }); expect(stale.ok).toBe(false); expect((await repository.findById(candidate.id))?.sections).toHaveLength(1); });
  it("archives and restores with durable events", async () => { const candidate = draft("page_lifecycle"); await repository.createWithEvent(candidate, createdEvent(candidate.id)); const archived = await repository.archiveWithEvent({ pageId: candidate.id, expectedVersion: 1, archivedAt: now, archivedBy: userId }, archivedEvent(candidate.id)); expect(archived.ok && archived.value.status).toBe("archived"); const restored = await repository.restoreWithEvent({ pageId: candidate.id, expectedVersion: 2, restoredAt: now, restoredBy: userId }, restoredEvent(candidate.id)); expect(restored.ok && restored.value.status).toBe("draft"); expect(await db.select().from(applicationOutbox)).toHaveLength(3); });
  it("rolls back aggregate creation when outbox insert fails", async () => { const candidate = draft("page_rollback"); const failing = new DrizzlePageRepository({ db, logger: new NoopLogger(), beforeOutboxInsert: () => { throw new Error("forced event failure"); } }); expect((await failing.createWithEvent(candidate, createdEvent(candidate.id))).ok).toBe(false); expect(await db.select().from(pages)).toHaveLength(0); expect(await db.select().from(applicationOutbox)).toHaveLength(0); });
  it("atomically replaces the previous homepage and emits a Website-scoped event", async () => { const first = draft("page_first", "first"); const second = draft("page_second", "second"); await repository.createWithEvent(first, createdEvent(first.id)); await repository.createWithEvent(second, createdEvent(second.id)); expect((await repository.setWebsiteHomepage({ websiteId, pageId: first.id, expectedPageVersion: 1, changedAt: now, changedBy: userId, event: homepageEvent(first.id) })).ok).toBe(true); const switched = await repository.setWebsiteHomepage({ websiteId, pageId: second.id, expectedPageVersion: 1, changedAt: now, changedBy: userId, event: homepageEvent(second.id) }); expect(switched.ok && switched.value.isHomepage && switched.value.version).toBe(2); expect((await repository.findById(first.id))?.isHomepage).toBe(false); expect((await repository.findById(first.id))?.version).toBe(3); const events = await db.select().from(applicationOutbox); expect(events.filter((event) => event.event_type === "website.homepage_changed")).toHaveLength(2); expect(events.at(-1)).toMatchObject({ aggregate_type: "website", aggregate_id: websiteId }); });
  it("enforces one active homepage and optimistic concurrency", async () => { const first = draft("page_first", "first"); const second = draft("page_second", "second"); await repository.createWithEvent(first, createdEvent(first.id)); await repository.createWithEvent(second, createdEvent(second.id)); await repository.setWebsiteHomepage({ websiteId, pageId: first.id, expectedPageVersion: 1, changedAt: now, changedBy: userId, event: homepageEvent(first.id) }); expect((await repository.setWebsiteHomepage({ websiteId, pageId: second.id, expectedPageVersion: 99, changedAt: now, changedBy: userId, event: homepageEvent(second.id) })).ok).toBe(false); await expect(db.update(pages).set({ is_homepage: true }).where(eq(pages.id, String(second.id)))).rejects.toThrow(); });
  it("rolls back both homepage flags when outbox insertion fails", async () => { const first = draft("page_first", "first"); const second = draft("page_second", "second"); await repository.createWithEvent(first, createdEvent(first.id)); await repository.createWithEvent(second, createdEvent(second.id)); await repository.setWebsiteHomepage({ websiteId, pageId: first.id, expectedPageVersion: 1, changedAt: now, changedBy: userId, event: homepageEvent(first.id) }); const failing = new DrizzlePageRepository({ db, logger: new NoopLogger(), beforeOutboxInsert: () => { throw new Error("forced event failure"); } }); expect((await failing.setWebsiteHomepage({ websiteId, pageId: second.id, expectedPageVersion: 1, changedAt: now, changedBy: userId, event: homepageEvent(second.id) })).ok).toBe(false); expect((await repository.findById(first.id))?.isHomepage).toBe(true); expect((await repository.findById(second.id))?.isHomepage).toBe(false); });
});
